services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=wood_track_docker_v1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=woodtrack123
    ports:
      - 5000:5432
    networks:
      - woodtracknet

  rabbitMQ:
    image: rabbitmq:3-management
    container_name: "rabbitmqcontainer"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
    expose:
      - 5672
    networks:
      - woodtracknet

  rabbitmq-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: WoodTrack.Subscriber\Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=wood.track.app@gmail.com
      - SMTP_PASSWORD=vnhb nvnk fcrq ywgj
      - ENABLE_SSL=true
      - MAIL_TIMEOUT=10000
      - MAIL_FROM_ADDRESS=no-replay@wood_track.ba
      - MAIL_DISPLAY_NAME=wood_track.ba
    depends_on:
      - rabbitMQ
      - postgres
    networks:
      - woodtracknet

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: WoodTrack.Api\Dockerfile
    environment:
      - ConnectionStrings__Main=Host=postgres;Port=5432;Database=wood_track_docker_v1;Username=postgres;Password=woodtrack123;Pooling=true
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=wood.track.app@gmail.com
      - SMTP_PASSWORD=vnhb nvnk fcrq ywgj
      - ENABLE_SSL=true
      - MAIL_TIMEOUT=10000
      - MAIL_FROM_ADDRESS=no-replay@wood_track.ba
      - MAIL_DISPLAY_NAME=wood_track.ba
    ports:
      - 5100:80
    networks:
      - woodtracknet
    depends_on:
      - postgres

networks:
  woodtracknet:
    driver: bridge
